### ISSUE TITLE
There are some errors, how to fix it?

### ISSUE THREAD

**Issue by wmydz1** [jinfagang/weibo_terminater#21]
can not find PhantomJS driver, please download from http://phantomjs.org/download.html based on your system.
all accounts getting cookies finished. starting scrap..
[Errno 2] No such file or directory: 'settings/cookies.pkl'
error, not find cookies file.
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    dispatcher.execute()
  File "/Users/samchen/Documents/weibo-crawer/weibo_terminater/core/dispatch_center.py", line 50, in execute
    self._init_single_mode()
  File "/Users/samchen/Documents/weibo-crawer/weibo_terminater/core/dispatch_center.py", line 93, in _init_single_mode
    scraper = WeiBoScraper(using_account=self.all_accounts[0], uuid=self.user_id, filter_flag=self.filter_flag)
AttributeError: 'Dispatcher' object has no attribute 'all_accounts'

**Comment by wmydz1** [comment]
It works! change PHANTOM_JS_PATH to my PHANTOM install path!

settings/config.py

Default path is PHANTOM_JS_PATH = '/Users/jintian/phantomjs-2.1.1-macosx/bin/phantomjs'

**Comment by jinfagang** [comment]
Glad you worked out.
