### ISSUE TITLE
Mac OS平台下 PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by liuyijiang1994** [jinfagang/weibo_terminater#30]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/peco/PycharmProjects/weibo_terminater/tests.py", line 51, in <module>
    test()
  File "/Users/peco/PycharmProjects/weibo_terminater/tests.py", line 27, in test
    cookies = get_cookie_from_network(accounts[0]['id'], accounts[0]['password'])
  File "/Users/peco/PycharmProjects/weibo_terminater/utils/cookies.py", line 49, in get_cookie_from_network
    driver = webdriver.PhantomJS(phantom_js_driver_file)
  File "/Users/peco/anaconda/envs/tensorflow_3.4/lib/python3.4/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 52, in __init__
    self.service.start()
  File "/Users/peco/anaconda/envs/tensorflow_3.4/lib/python3.4/site-packages/selenium/webdriver/common/service.py", line 86, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'phantomjs' executable may have wrong permissions.

**Comment by liuyijiang1994** [comment]
解决了 phantomjs路径应该是bin的路径
PHANTOM_JS_PATH = '/Users/peco/Documents/phantomjs/bin/phantomjs'

**Comment by yovenny** [comment]
坑呀，readme写的不够清楚，好多人都认为是根路径，新手一枚。

**Comment by jinfagang** [comment]
@yovenny in config.py I specific that path should be executable path
