### ISSUE TITLE
尝试运行失败，日志如下

### ISSUE THREAD

**Issue by yovenny** [jinfagang/weibo_terminater#41]
```
skyArraondeMacBook-Pro:weibo_terminater skyArraon$ python3 main.py -i 2956950657
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    from core.dispatch_center import Dispatcher
  File "/Users/skyArraon/Downloads/tech/python/weibo_terminater/core/dispatch_center.py", line 19, in <module>
    from scraper.weibo_scraper import WeiBoScraper
  File "/Users/skyArraon/Downloads/tech/python/weibo_terminater/scraper/weibo_scraper.py", line 34, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
```

**Comment by jinfagang** [comment]
You'd better install lxml first.
