### ISSUE TITLE
运行命令python3 main.py -i realangelababy时候报错

### ISSUE THREAD

**Issue by shejay2017** [jinfagang/weibo_terminater#47]
出现错误：error, account id 5403168675 is not valid, pass this account, you can edit it and then update cookies.

请问这是什么原因啊，微博账号在网页能正常登陆，

**Comment by jinfagang** [comment]
Account id is your login username, not the weibo id.

**Comment by shejay2017** [comment]
谢谢你的回复，这个我也换成过微博账号，也还是报错，完整的错误是这样的：
error, account id 18275209699 is not valid, pass this account, you can edit it and then update cookies. 
all accounts getting cookies finished. starting scrap..
[Errno 2] No such file or directory: 'settings/cookies.pkl'
error, not find cookies file.
Traceback (most recent call last):
  File "main.py", line 56, in <module>
    dispatcher.execute()
  File "/root/weibo_terminater/core/dispatch_center.py", line 50, in execute
    self._init_single_mode()
  File "/root/weibo_terminater/core/dispatch_center.py", line 93, in _init_single_mode
    scraper = WeiBoScraper(using_account=self.all_accounts[0], uuid=self.user_id, filter_flag=self.filter_flag)
AttributeError: 'Dispatcher' object has no attribute 'all_accounts'

**Comment by jinfagang** [comment]
Should install PhantomJS first, we using this to get cookies automatically.

**Comment by xnzmc** [comment]
I came up with the same problem, and I'm pretty sure that PhantomJs is installed correctly and config.py is modified correctly.
This is really confusing to me. And  I guess maybe the internet condition/speed is related?

**Comment by cheersrong** [comment]
hi，xnzmc! I also meet this problem. Have you already fix it?

**Comment by ray0807** [comment]
初步怀疑是ip（可能被禁止）问题

**Comment by mansonami** [comment]
try:
            cookie_list = driver.get_cookies()
            print(cookie_list)
这里得不到？
